# Generated by Django 5.2.7 on 2025-10-06 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_tyope', models.CharField(choices=[('BOOK', 'Livro'), ('MOVIE', 'Filme'), ('Game', 'jogo')], max_length=5)),
                ('title', models.CharField(max_length=200)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('logged_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
