# Generated by Django 5.2.7 on 2025-10-06 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logentry',
            old_name='media_tyope',
            new_name='media_type',
        ),
    ]
